### ISSUE TITLE
Audio classifier not working

### ISSUE THREAD

**Issue by TMills2** [edgeimpulse/example-standalone-inferencing-linux#11]
I am attempting to classify audio data in real-time on a raspberry pi 4. I was previously able to get it to work last month by following the instructions provided. However, I am unsure if it is the git repository that has changed or the files included in the edge impulse c++ deployment but, whenever I run the "APP_AUDIO=1 make -j" command I get this output. And the Build directory isn't created.
![2023-03-19-161443_1920x1080_scrot](https://user-images.githubusercontent.com/122755153/226206604-b0365285-23fd-4514-8667-6d31baafe02a.png)

**Comment by TMills2** [comment]
Update: I believe it has to do with more recent changes to c++ deployments. Older deployments of previous models still work but newer deployments do not.

**Comment by janjongboom** [comment]
Fixed in https://github.com/edgeimpulse/example-standalone-inferencing-linux/pull/20
