### ISSUE TITLE
Cannot Build EIM model

### ISSUE THREAD

**Issue by EClemMarq** [edgeimpulse/example-standalone-inferencing-linux#14]
I am using a Jetson Nano, trying to generate an EIM from a custom Keras model.

TensorRT version 8

When I try to run `APP_EIM=1 TARGET_JETSON_NANO=1 make -j`, I get the error

`In file included from ./edge-impulse-sdk/classifier/ei_fil_result_struct.h:25: ./model-parameters/model_variables.h:58:19: error: use of undeclared identifier 'trained_onnx_arena_size`

What would be causing this error?  Thank you

**Comment by AIWintermuteAI** [comment]
There was an issue with a TensorRT deployment model_variables, it has now been corrected (arena size is set to 0 for TensorRT).
